name: Push Main Branch to NPM Package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: npm ci
      - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-actions[bot]"
      - run: npm version patch -m "Auto bump version to %s for NPM deploy CI"
      - run: git push --follow-tags
      - run: npm publish
        env:
          NPM_AUTOMATION: ${{ secrets.NPM_AUTOMATION }}
